"""Parse Nextflow DAG DOT files to extract canonical DAG structure."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, TypedDict

from app.utils.logging import get_logger
from app.utils.dag_builder import (
    build_canonical_dag,
    clean_process_label,
    normalize_dag_id,
)

logger = get_logger(__name__)


class DagNodeData(TypedDict, total=False):
    label: str
    displayLabel: str
    status: str
    inputs: dict[str, str]
    outputs: dict[str, str]
    container: str


class DagNode(TypedDict):
    id: str
    type: str
    position: dict[str, float]
    data: DagNodeData


class DagEdge(TypedDict, total=False):
    id: str
    source: str
    target: str
    animated: bool


class DagResult(TypedDict):
    nodes: list[DagNode]
    edges: list[DagEdge]


class DagParser:
    """Parse Nextflow DAG DOT files to extract DAG structure."""

    def parse_dot_file(
        self,
        dot_path: str | Path,
        *,
        schema: dict[str, Any] | None = None,
    ) -> DagResult:
        """Parse a Nextflow DAG DOT file.

        Args:
            dot_path: Path to dag.dot file generated by -with-dag

        Returns:
            Dict with nodes and edges in React Flow format
        """
        dot_path = Path(dot_path)
        if not dot_path.exists():
            logger.warning("dag.dot_not_found", path=str(dot_path))
            return {"nodes": [], "edges": []}

        try:
            content = dot_path.read_text()
            return self._parse_dot_content(content, schema=schema)
        except Exception as e:
            logger.error("dag.dot_parse_error", path=str(dot_path), error=str(e))
            return {"nodes": [], "edges": []}

    def _parse_dot_content(
        self,
        content: str,
        *,
        schema: dict[str, Any] | None = None,
    ) -> DagResult:
        """Parse DOT format content."""
        dot_nodes: dict[str, str] = {}
        edges: list[dict[str, str]] = []

        # Parse nodes: p0 [label="PROCESS_NAME"]
        node_pattern = re.compile(r'(\w+)\s*\[label="([^"]+)"\]')
        for match in node_pattern.finditer(content):
            node_id = match.group(1)
            label = match.group(2)
            process_name = self._clean_process_label(label)
            dot_nodes[node_id] = process_name

        # Parse edges: p0 -> p1
        edge_pattern = re.compile(r"(\w+)\s*->\s*(\w+)")
        for match in edge_pattern.finditer(content):
            source_dot_id = match.group(1)
            target_dot_id = match.group(2)

            if source_dot_id in dot_nodes and target_dot_id in dot_nodes:
                edges.append(
                    {
                        "source": dot_nodes[source_dot_id],
                        "target": dot_nodes[target_dot_id],
                    }
                )

        tasks = (
            schema.get("tasks", [])
            if schema and schema.get("tasks")
            else [{"name": name} for name in dot_nodes.values()]
        )

        return build_canonical_dag(tasks, edges)

    def _clean_process_label(self, label: str) -> str:
        """Clean process label from DOT file."""
        return clean_process_label(label)

    def update_node_status(
        self, dag: DagResult, process_name: str, status: str
    ) -> DagResult:
        """Update a node's status in the DAG.

        Args:
            dag: Current DAG dict with nodes and edges
            process_name: Name of the process to update
            status: New status (pending, running, success, failed)

        Returns:
            Updated DAG dict
        """
        process_id = normalize_dag_id(process_name)

        for node in dag.get("nodes", []):
            if node.get("id") == process_id:
                node["data"]["status"] = status
                break

        return dag

    @staticmethod
    def update_edge_animations(dag: DagResult) -> DagResult:
        """Update edge animations based on node statuses.

        Edges from running nodes should be animated.

        Args:
            dag: Current DAG dict with nodes and edges

        Returns:
            Updated DAG dict
        """
        nodes = dag.get("nodes", [])
        edges = dag.get("edges", [])

        # Build lookup for node status
        node_status = {
            node["id"]: node.get("data", {}).get("status", "pending") for node in nodes
        }

        for edge in edges:
            source_status = node_status.get(edge["source"], "pending")
            target_status = node_status.get(edge["target"], "pending")
            edge["animated"] = source_status == "running" or target_status == "running"

        return dag

    def create_empty_dag(self) -> DagResult:
        """Create an empty DAG structure."""
        return {"nodes": [], "edges": []}
