"""RunCompiler — the single code path from RunCreate envelope to a
persisted, queued Run.

Replaces the legacy ``RunSubmissionService.create_run_submission`` /
``create_run_unified`` (928 lines of hint-driven compilation) with a
direct, form_spec-driven compile:

    payload (RunCreate)
        → validate against Workflow.form_spec
        → resolve asset:// URIs to absolute paths
        → materialize table values as CSV, JSON inputs as .json
        → build adapter-ready config dict
        → construct the engine's launch spec (argv + env + cwd)
        → create Run row, persist audit artifacts, queue + dispatch

The compile step owns every file write that must exist before the
scheduler dispatches the run. Adapter contract (``build_command``,
``parse_event``, ``post_complete``, ``cancel``) is unchanged; we just
drive it at compile time so ``audit/launch.sh`` is a real, replayable
snapshot of what the scheduler will execute.
"""

from __future__ import annotations

import csv
import io
import json
import os
import shutil
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any, Mapping, Sequence

from sqlalchemy.ext.asyncio import AsyncSession

from app.engine.registry import get_adapter
from app.models.run import Run, RunStatus
from app.models.run_config import RunConfigHelper
from app.models.workflow import WorkflowEngine
from app.path_layout import (
    RunLayout,
    database_root,
    deliveries_root,
    ensure_run_layout,
    path_relative_to,
    project_home,
    project_data_root,
    project_run_uploads_root,
    reference_root,
    resolve_asset as resolve_asset_uri,
    safe_join,
    workflow_bundle_home,
    workflow_entrypoint_path,
)
from app.repositories.project_repo import ProjectRepository
from app.repositories.project_workflow_binding_repo import (
    ProjectWorkflowBindingRepository,
)
from app.repositories.run_repo import RunRepository
from app.repositories.workflow_repo import WorkflowRepository
from app.runtime.events import publish_run_status
from app.schemas.form_spec import FormField, FormSpec
from app.schemas.run import (
    RunCreate,
    RunErrorCode,
)
from app.services.audit_service import AuditService
from app.services.run_archive import RunArchiveService
from app.services.run_dispatch import RunDispatcher, get_run_dispatcher
from app.services.run_helpers import build_resolved_runspec, generate_run_id
from app.services.storage_service import StorageService
from app.services.workflow_form_spec import effective_workflow_form_spec
from app.services.container_registry_service import ContainerRegistryService
from app.services.workflow_image_service import (
    WorkflowImageRegistry,
    rewrite_wdl_static_container_literals,
    runtime_workflow_container_images,
    workflow_container_images,
    workflow_registry_from_auth_material,
)
from app.utils.project_access import can_access_project


@dataclass(frozen=True, slots=True)
class LaunchSpec:
    """Fully resolved command line for an engine invocation.

    Produced at compile time so ``audit/launch.sh`` matches exactly what
    the scheduler will run. The scheduler still invokes the adapter to
    obtain a fresh command (runtime paths can shift), but the compile-time
    snapshot is the source of truth for replay and debugging.
    """

    argv: tuple[str, ...]
    env: Mapping[str, str]
    cwd: Path
    engine: str

    def as_shell_script(self) -> str:
        import shlex

        lines = ["#!/usr/bin/env bash", "# Autogenerated by RunCompiler", ""]
        for key, value in sorted(self.env.items()):
            lines.append(f"export {key}={shlex.quote(value)}")
        lines.append(f"cd {shlex.quote(str(self.cwd))}")
        joined = " ".join(shlex.quote(arg) for arg in self.argv)
        lines.append("exec " + joined)
        lines.append("")
        return "\n".join(lines)


@dataclass(frozen=True, slots=True)
class CompiledRun:
    run: Run
    layout: RunLayout
    launch: LaunchSpec


@dataclass(frozen=True, slots=True)
class ValidatedRun:
    project: Any
    workflow: Any
    spec: FormSpec
    submitted_values: dict[str, Any]
    resolved_values: dict[str, Any]


class CompileError(ValueError):
    """Raised when a submission fails compile-time validation.

    Carries a stable ``code`` (from ``RunErrorCode``) so the API layer can
    translate it into a structured ``RunError`` body.
    """

    def __init__(self, code: str, message: str, *, hint: str | None = None):
        super().__init__(message)
        self.code = code
        self.hint = hint


class WorkflowNotEnabledError(Exception):
    """The workflow is not bound to the project."""


class RunCompiler:
    def __init__(
        self,
        session: AsyncSession,
        *,
        dispatcher: RunDispatcher | None = None,
    ):
        self.session = session
        self.project_repo = ProjectRepository(session)
        self.workflow_repo = WorkflowRepository(session)
        self.binding_repo = ProjectWorkflowBindingRepository(session)
        self.run_repo = RunRepository(session)
        self.storage = StorageService(session)
        self.archive = RunArchiveService(session)
        self.dispatcher = dispatcher or get_run_dispatcher()

    async def create_run(
        self,
        payload: RunCreate,
        *,
        user_id: str | None = None,
        workspace_id: str | None = None,
        priority: str = "normal",
        config_overrides: dict | None = None,
        extra_config: dict | None = None,
        audit_action: str | None = None,
        audit_details: dict | None = None,
        source_run_id: str | None = None,
        replay_kind: str | None = None,
        replay_idempotency_key: str | None = None,
        attempt_number: int = 1,
    ) -> Run:
        """Compile the envelope, persist the run, and queue it for dispatch."""
        if payload.options and payload.options.resume_from_run_id:
            raise CompileError(
                RunErrorCode.INVALID_FORM_VALUES,
                "options.resume_from_run_id is not supported on run creation",
                hint="Use POST /runs/{run_id}/resume to resume a failed run.",
            )
        validated = await self.validate(
            payload,
            user_id=user_id,
            workspace_id=workspace_id,
        )
        compiled = await self._compile(
            payload,
            validated=validated,
            config_overrides=config_overrides,
            extra_config=extra_config,
            source_run_id=source_run_id,
            replay_kind=replay_kind,
            replay_idempotency_key=replay_idempotency_key,
            attempt_number=attempt_number,
        )
        return await self._persist(
            compiled,
            payload,
            user_id=user_id,
            priority=priority,
            audit_action=audit_action,
            audit_details=audit_details,
        )

    async def validate(
        self,
        payload: RunCreate,
        *,
        user_id: str | None = None,
        workspace_id: str | None = None,
    ) -> ValidatedRun:
        project = await self.project_repo.get(str(payload.project_id))
        if project is None or not can_access_project(
            project,
            user_id=user_id,
            workspace_id=workspace_id,
        ):
            raise FileNotFoundError("project not found")

        workflow = await self.workflow_repo.get(str(payload.workflow_id))
        if workflow is None:
            raise FileNotFoundError("workflow not found")

        if not await self.binding_repo.is_enabled(
            project_id=str(payload.project_id),
            workflow_id=str(payload.workflow_id),
        ):
            raise WorkflowNotEnabledError("workflow not enabled for project")

        spec = effective_workflow_form_spec(workflow)
        submitted_values = _merge_values_with_defaults(payload.values, spec)
        _validate_form_values(submitted_values, spec)
        resolved_values = await self._resolve_values(
            submitted_values,
            spec,
            project_id=str(payload.project_id),
            workflow=workflow,
        )
        return ValidatedRun(
            project=project,
            workflow=workflow,
            spec=spec,
            submitted_values=submitted_values,
            resolved_values=resolved_values,
        )

    # ── compile ────────────────────────────────────────────────────────────

    async def _compile(
        self,
        payload: RunCreate,
        *,
        validated: ValidatedRun,
        config_overrides: dict | None = None,
        extra_config: dict | None = None,
        source_run_id: str | None = None,
        replay_kind: str | None = None,
        replay_idempotency_key: str | None = None,
        attempt_number: int = 1,
    ) -> CompiledRun:
        project = validated.project
        workflow = validated.workflow
        spec = validated.spec
        engine = str(getattr(workflow.engine, "value", workflow.engine))

        workspace_path = project_home(project)
        run_id, layout = _reserve_fresh_run_layout(project, engine=engine)
        resolved_values = self._materialize_runtime_inputs(
            validated.resolved_values,
            workflow=workflow,
            spec=spec,
            layout=layout,
            project=project,
        )

        # ── values → engine inputs ────────────────────────────────────────
        params, inputs, samples_count = self._build_engine_inputs(
            workflow=workflow,
            engine=engine,
            spec=spec,
            resolved_values=resolved_values,
            layout=layout,
            workspace_path=workspace_path,
            run_id=run_id,
        )

        # ── persist engine-native input documents ──────────────────────────
        if engine == WorkflowEngine.WDL.value:
            self._write_json(layout.engine_workspace.parent / "inputs.json", inputs)

        # ── assemble run.config ────────────────────────────────────────────
        options = payload.options
        config_overrides = dict(config_overrides or {})
        config = RunConfigHelper.build_v1(
            params=params,
            inputs=inputs,
            config_overrides=config_overrides,
            resolved_runspec=build_resolved_runspec(
                workspace_path=workspace_path, params=params, inputs=inputs
            ),
            values=validated.submitted_values,
            options=options.model_dump(mode="json", exclude_none=True)
            if options
            else None,
            retry_policy=(
                {"max_retries": options.max_retries}
                if options and options.max_retries is not None
                else None
            ),
            timeout_seconds=options.timeout_seconds if options else None,
        )
        if (
            engine == WorkflowEngine.NEXTFLOW.value
            and options
            and _optional_text(options.profile)
        ):
            config["profile"] = str(options.profile).strip()
        image_registry = await self._resolve_workflow_image_registry(
            workflow,
            project_id=str(payload.project_id),
        )
        if engine == WorkflowEngine.NEXTFLOW.value and image_registry is not None:
            _set_config_override(
                config,
                "docker.registry",
                image_registry.image_prefix,
            )
        config = self._enrich_runtime(
            config,
            workflow=workflow,
            workspace_path=workspace_path,
            layout=layout,
            run_id=run_id,
            engine=engine,
            image_registry=image_registry,
        )
        if extra_config:
            config = _merge_config_patch(config, extra_config)

        # ── build launch spec via adapter ──────────────────────────────────
        # Run pre_submit + build_command here (not just at dispatch) so
        # audit/launch.sh is a faithful snapshot. The scheduler re-runs both
        # at dispatch to pick up anything environment-dependent (e.g. Docker
        # availability) that shifted between compile and execute.
        adapter = get_adapter(engine)
        launch_config = deepcopy(config)
        if engine == WorkflowEngine.WDL.value:
            launch_runtime = dict(launch_config.get("runtime") or {})
            launch_runtime["pull_required_images"] = False
            launch_config["runtime"] = launch_runtime
        prepared = await adapter.pre_submit(launch_config, str(workspace_path))
        prepared.pop("__engine_logs__", None)
        argv = await adapter.build_command(prepared, str(workspace_path))
        launch = LaunchSpec(
            argv=tuple(str(arg) for arg in argv),
            env={},
            cwd=workspace_path,
            engine=engine,
        )

        config["launch"] = {
            "argv": list(launch.argv),
            "cwd": str(launch.cwd),
            "engine": launch.engine,
        }

        # Create the Run row but don't queue yet — the caller (persist) wires
        # the archive, audit log, and dispatch in the right order.
        run = Run(
            run_id=run_id,
            project_id=str(payload.project_id),
            workflow_id=str(payload.workflow_id),
            status=RunStatus.PENDING.value,
            config=config,
            samples_count=samples_count,
            tasks_total=0,
            tasks_completed=0,
            source_run_id=source_run_id,
            replay_kind=replay_kind,
            replay_idempotency_key=replay_idempotency_key,
            attempt_number=max(1, int(attempt_number or 1)),
        )
        return CompiledRun(run=run, layout=layout, launch=launch)

    # ── persist ────────────────────────────────────────────────────────────

    async def _persist(
        self,
        compiled: CompiledRun,
        payload: RunCreate,
        *,
        user_id: str | None,
        priority: str,
        audit_action: str | None = None,
        audit_details: dict | None = None,
    ) -> Run:
        # write the launch script before the DB row so audit/launch.sh is
        # durable even if the scheduler never picks the run up
        compiled.layout.audit.mkdir(parents=True, exist_ok=True)
        (compiled.layout.audit / "launch.sh").write_text(
            compiled.launch.as_shell_script(), encoding="utf-8"
        )

        run = await self.run_repo.create(
            run_id=compiled.run.run_id,
            project_id=str(payload.project_id),
            workflow_id=str(payload.workflow_id),
            status=RunStatus.PENDING.value,
            config=compiled.run.config,
            samples_count=compiled.run.samples_count,
            tasks_total=0,
            tasks_completed=0,
            source_run_id=compiled.run.source_run_id,
            replay_kind=compiled.run.replay_kind,
            replay_idempotency_key=compiled.run.replay_idempotency_key,
            attempt_number=compiled.run.attempt_number,
        )

        workspace_path = project_home(
            await self.project_repo.get(str(payload.project_id))
        )
        await self.archive.persist_run_archive(
            run=run,
            workspace_path=workspace_path,
            engine=compiled.launch.engine,
        )

        run = await self.run_repo.update(run, status=RunStatus.QUEUED.value)
        audit = AuditService(self.session)
        await audit.log(
            action="run.created",
            resource_type="run",
            resource_id=run.run_id,
            project_id=str(run.project_id),
            actor="api",
            details={
                "status": RunStatus.QUEUED.value,
                "engine": compiled.launch.engine,
            },
        )
        if audit_action:
            await audit.log(
                action=audit_action,
                resource_type="run",
                resource_id=run.run_id,
                project_id=str(run.project_id),
                actor="api",
                details=audit_details or {},
            )
        await publish_run_status(run, message="Run queued")
        self.dispatcher.dispatch(run.run_id, priority=priority)
        return run

    # ── helpers ────────────────────────────────────────────────────────────

    async def _resolve_values(
        self,
        values: dict[str, Any],
        spec: FormSpec,
        *,
        project_id: str,
        workflow=None,
    ) -> dict[str, Any]:
        """Walk form values, resolving asset:// URIs and flagging bad paths."""
        project = await self.project_repo.get(project_id)
        if project is None:
            raise FileNotFoundError("project not found")

        fields_by_id = {field.id: field for field in spec.fields}
        resolved: dict[str, Any] = {}

        for field_id, raw in values.items():
            field = fields_by_id.get(field_id)
            if field is not None and field.platform_managed:
                continue

            if field is not None and field.kind == "table" and isinstance(raw, dict):
                resolved[field_id] = await self._resolve_table(
                    raw,
                    field=field,
                    project=project,
                    project_id=project_id,
                    workflow=workflow,
                )
                continue

            if (
                field is not None
                and field.kind == "file_list"
                and isinstance(raw, list)
            ):
                resolved[field_id] = [
                    await self._resolve_path_cell(
                        item,
                        project=project,
                        project_id=project_id,
                        field=field,
                        workflow=workflow,
                    )
                    for item in raw
                    if item is not None
                ]
                continue

            if (
                field is not None
                and field.kind in ("file", "directory")
                and raw is not None
            ):
                resolved[field_id] = await self._resolve_path_cell(
                    raw,
                    project=project,
                    project_id=project_id,
                    field=field,
                    workflow=workflow,
                )
                continue

            resolved[field_id] = raw

        return resolved

    async def _resolve_table(
        self,
        raw: dict[str, Any],
        *,
        field: FormField,
        project,
        project_id: str,
        workflow,
    ) -> dict[str, Any]:
        rows = raw.get("rows") if isinstance(raw.get("rows"), list) else []
        path_columns = {
            column.name for column in (field.columns or []) if column.kind == "path"
        }
        resolved_rows: list[dict[str, str]] = []
        for row in rows:
            if not isinstance(row, dict):
                continue
            resolved_row: dict[str, str] = {}
            for key, value in row.items():
                if key in path_columns:
                    resolved_row[str(key)] = await self._resolve_path_cell(
                        value,
                        project=project,
                        project_id=project_id,
                        field=field,
                        workflow=workflow,
                    )
                else:
                    resolved_row[str(key)] = "" if value is None else str(value)
            resolved_rows.append(resolved_row)
        return {
            "filename": str(raw.get("filename") or f"{field.id}.csv"),
            "rows": resolved_rows,
        }

    async def _resolve_path_cell(
        self,
        value: Any,
        *,
        project_id: str,
        project=None,
        field: FormField | None = None,
        workflow=None,
    ) -> str:
        if not isinstance(value, str):
            return "" if value is None else str(value)
        text = value.strip()
        if text == "":
            return ""
        is_workflow_asset = text.startswith("asset://workflow/")
        is_run_upload_asset = text.startswith("asset://run_upload/")
        try:
            if text.startswith("asset://"):
                if is_workflow_asset:
                    candidate = self._resolve_workflow_asset(
                        text,
                        workflow=workflow,
                    )
                elif is_run_upload_asset:
                    project = project or await self.project_repo.get(project_id)
                    if project is None:
                        raise FileNotFoundError("project not found")
                    candidate = resolve_asset_uri(project, text).path
                else:
                    resolved = await self.storage.resolve_asset(
                        project_id=project_id, uri=text
                    )
                    candidate = Path(resolved.path)
            else:
                if field is None:
                    return text
                if not field.allow_roots:
                    return text
                project = project or await self.project_repo.get(project_id)
                if project is None:
                    raise FileNotFoundError("project not found")
                candidate = self._resolve_manual_path(
                    text, project=project, field=field
                )
        except FileNotFoundError as exc:
            code = (
                RunErrorCode.ASSET_NOT_FOUND
                if text.startswith("asset://")
                else RunErrorCode.PATH_OUTSIDE_ALLOWED_ROOT
            )
            raise CompileError(
                code,
                str(exc),
                hint=(
                    "Re-select the file in the browser; the source may have changed."
                    if text.startswith("asset://")
                    else "Choose an existing path from allowed project/reference storage."
                ),
            ) from exc

        if (
            is_workflow_asset
            or is_run_upload_asset
            or field is None
            or not field.allow_roots
        ):
            return str(candidate)
        self._validate_allowed_path(candidate, project=project, field=field)
        return str(candidate)

    def _materialize_runtime_inputs(
        self,
        resolved_values: dict[str, Any],
        *,
        workflow,
        spec: FormSpec,
        layout: RunLayout,
        project,
    ) -> dict[str, Any]:
        if str(getattr(workflow.source, "value", workflow.source)) != "local":
            bundle_root: Path | None = None
        else:
            bundle_root = workflow_bundle_home(str(workflow.id)).resolve()

        fields_by_id = {field.id: field for field in spec.fields}
        materialized: dict[str, Any] = {}

        for field_id, value in resolved_values.items():
            field = fields_by_id.get(field_id)
            if field is None:
                materialized[field_id] = deepcopy(value)
                continue
            if field.kind == "table" and isinstance(value, dict):
                path_columns = {
                    column.name
                    for column in (field.columns or [])
                    if column.kind == "path"
                }
                rows: list[dict[str, Any]] = []
                for row in list(value.get("rows") or []):
                    if not isinstance(row, dict):
                        continue
                    materialized_row: dict[str, Any] = {}
                    for key, cell in row.items():
                        if key in path_columns:
                            materialized_row[key] = self._copy_bundle_asset_to_run(
                                cell,
                                bundle_root=bundle_root,
                                layout=layout,
                            )
                        else:
                            materialized_row[key] = deepcopy(cell)
                    rows.append(materialized_row)
                materialized[field_id] = {
                    "filename": str(value.get("filename") or f"{field_id}.csv"),
                    "rows": rows,
                }
                continue
            if field.kind == "file_list" and isinstance(value, list):
                materialized[field_id] = [
                    self._copy_bundle_asset_to_run(
                        item, bundle_root=bundle_root, layout=layout
                    )
                    for item in value
                ]
                continue
            if field.kind in ("file", "directory"):
                staged = self._copy_bundle_asset_to_run(
                    value,
                    bundle_root=bundle_root,
                    layout=layout,
                )
                if field.materialize_to_run:
                    staged = self._copy_runtime_document_to_run(
                        staged,
                        field_id=field_id,
                        project=project,
                        layout=layout,
                    )
                materialized[field_id] = staged
                continue
            materialized[field_id] = deepcopy(value)

        return materialized

    def _copy_bundle_asset_to_run(
        self,
        value: Any,
        *,
        bundle_root: Path | None,
        layout: RunLayout,
    ) -> Any:
        if bundle_root is None:
            return value
        if not isinstance(value, str) or not value.strip():
            return value
        candidate = Path(value).expanduser().resolve(strict=False)
        if not candidate.exists() or not candidate.is_relative_to(bundle_root):
            return value

        destination = (
            layout.materialized / "workflow" / candidate.relative_to(bundle_root)
        )
        if candidate.is_dir():
            if destination.exists():
                shutil.rmtree(destination)
            shutil.copytree(candidate, destination)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(candidate, destination)
        return str(destination)

    def _copy_runtime_document_to_run(
        self,
        value: Any,
        *,
        field_id: str,
        project,
        layout: RunLayout,
    ) -> Any:
        if not isinstance(value, str) or not value.strip():
            return value

        candidate = Path(value).expanduser().resolve(strict=False)
        if not candidate.exists():
            return value

        attachments_root = layout.materialized_attachments.resolve()
        if candidate.is_relative_to(attachments_root):
            return str(candidate)

        destination = attachments_root / field_id / candidate.name
        if candidate.is_dir():
            if destination.exists():
                shutil.rmtree(destination)
            shutil.copytree(candidate, destination)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(candidate, destination)

        upload_root = project_run_uploads_root(project).resolve()
        if candidate.is_relative_to(upload_root):
            self._cleanup_staged_run_upload(candidate, upload_root=upload_root)

        return str(destination)

    @staticmethod
    def _cleanup_staged_run_upload(candidate: Path, *, upload_root: Path) -> None:
        for ancestor in (candidate, *candidate.parents):
            if ancestor == upload_root:
                break
            if ancestor.is_file():
                ancestor.unlink(missing_ok=True)
                continue
            try:
                ancestor.rmdir()
            except OSError:
                break

    def _resolve_workflow_asset(self, uri: str, *, workflow) -> Path:
        if workflow is None:
            raise FileNotFoundError("workflow asset source unavailable")

        workflow_id = str(getattr(workflow, "id", "") or "").strip()
        remainder = uri.removeprefix("asset://workflow/")
        asset_workflow_id, sep, nested = remainder.partition("/")
        if not sep or not asset_workflow_id or asset_workflow_id != workflow_id:
            raise FileNotFoundError("workflow asset not found")
        if not nested.strip():
            raise FileNotFoundError("workflow asset path not provided")

        try:
            candidate = safe_join(
                workflow_bundle_home(workflow_id),
                nested,
                escape_message="workflow asset escapes bundle",
            )
        except PermissionError as exc:
            raise FileNotFoundError("workflow asset not found") from exc
        if not candidate.exists():
            raise FileNotFoundError(f"workflow asset not found: {uri}")
        return candidate

    def _build_engine_inputs(
        self,
        *,
        workflow,
        engine: str,
        spec: FormSpec,
        resolved_values: dict[str, Any],
        layout: RunLayout,
        workspace_path: Path,
        run_id: str,
    ) -> tuple[dict[str, Any], dict[str, Any], int]:
        """Map resolved values to engine-specific ``params`` / ``inputs`` dicts.

        * WDL — inputs are qualified under ``<workflow_name>.<field>`` and
          include platform-managed ``outdir``; samplesheet-like table fields
          are first written to disk, then passed as an absolute path.
        * Nextflow — params are keyed by the raw field id and a samplesheet
          table field is materialised into ``input/attachments/`` with its
          relative path stored in params.
        """
        fields_by_id = {field.id: field for field in spec.fields}
        outdir = (
            str(layout.results.resolve())
            if engine == WorkflowEngine.WDL.value
            else path_relative_to(workspace_path, layout.results)
        )
        params: dict[str, Any] = {"outdir": outdir}
        inputs: dict[str, Any] = {}
        samples_count = 0

        for field_id, value in resolved_values.items():
            field = fields_by_id.get(field_id)
            key = (field.engine_key or field.id) if field is not None else field_id

            if isinstance(value, dict) and "rows" in value:  # table
                rows: list[dict[str, str]] = list(value.get("rows") or [])
                samples_count = len([row for row in rows if any(row.values())])
                csv_dest = layout.attachments / str(
                    value.get("filename") or f"{field_id}.csv"
                )
                csv_dest.parent.mkdir(parents=True, exist_ok=True)
                csv_dest.write_text(_render_csv(rows), encoding="utf-8")
                rel = path_relative_to(workspace_path, csv_dest)
                if engine == WorkflowEngine.WDL.value:
                    inputs[key] = str(csv_dest)
                else:
                    params[key] = rel
                continue

            if engine == WorkflowEngine.WDL.value:
                inputs[key] = value
            else:
                params[key] = value

        if engine == WorkflowEngine.WDL.value:
            inputs.update(
                self._platform_managed_wdl_inputs(
                    workflow=workflow,
                    outdir=outdir,
                )
            )

        return params, inputs, samples_count

    def _platform_managed_wdl_inputs(self, *, workflow, outdir: str) -> dict[str, str]:
        schema = getattr(workflow, "schema_json", None) or {}
        workflow_name = str(schema.get("workflow_name") or "")
        managed: dict[str, str] = {}
        for item in list(schema.get("inputs") or []):
            if not isinstance(item, dict) or not item.get("is_internal"):
                continue
            name = str(item.get("name") or "").strip()
            if not name:
                continue
            if name.lower() in {"outdir", "output_dir", "publish_dir", "work_dir"}:
                qualified = (
                    f"{workflow_name}.{name}"
                    if workflow_name and "." not in name
                    else name
                )
                managed[qualified] = outdir
        return managed

    def _enrich_runtime(
        self,
        config: dict,
        *,
        workflow,
        workspace_path: Path,
        layout: RunLayout,
        run_id: str,
        engine: str,
        image_registry: WorkflowImageRegistry | None = None,
    ) -> dict:
        """Add runtime paths the adapter needs at command-build time.

        The scheduler re-enriches these at dispatch time, so this mirror is
        for the compile-time ``build_command`` call (and for audit).
        """
        runtime = dict(config.get("runtime") or {})
        runtime["dag_path"] = str(
            (layout.audit / "dag.dot").relative_to(workspace_path)
        )
        runtime["trace_path"] = str(
            (layout.audit / "trace.tsv").relative_to(workspace_path)
        )
        runtime["work_dir"] = str(layout.engine_workspace.relative_to(workspace_path))
        required_images = _required_container_images(
            getattr(workflow, "schema_json", None),
            image_registry=image_registry,
        )
        if required_images:
            runtime["required_images"] = required_images
        if engine == WorkflowEngine.WDL.value:
            runtime["wdl_work_dir"] = str(
                layout.engine_workspace.relative_to(workspace_path)
            )

        workflow_path = ""
        source_value = getattr(workflow.source, "value", workflow.source)
        if str(source_value) == "local" and getattr(
            workflow, "entrypoint_relpath", None
        ):
            workflow_path = str(workflow_entrypoint_path(workflow))
        elif getattr(workflow, "source_ref", None):
            workflow_path = str(workflow.source_ref)

        config = dict(config)
        if (
            engine == WorkflowEngine.WDL.value
            and workflow_path
            and image_registry is not None
        ):
            workflow_path = str(
                _write_resolved_wdl_workflow(
                    Path(workflow_path),
                    layout=layout,
                    image_registry=image_registry,
                )
            )
            runtime["resolved_workflow_path"] = workflow_path
        source_value = str(getattr(workflow.source, "value", workflow.source))
        revision = _optional_nextflow_revision(getattr(workflow, "version", None))
        if (
            engine == WorkflowEngine.NEXTFLOW.value
            and source_value != "local"
            and revision
        ):
            config["revision"] = revision
            runtime["revision"] = revision
        config["runtime"] = runtime
        config["run_id"] = run_id
        config["engine"] = engine
        config["pipeline"] = workflow_path or workflow.name
        config["workflow_path"] = workflow_path
        config["work_dir"] = runtime["work_dir"]
        config["outdir"] = RunConfigHelper(config).params.get("outdir") or "results"
        config["options"] = dict(config.get("options") or {})
        return config

    async def _resolve_workflow_image_registry(
        self,
        workflow,
        *,
        project_id: str,
    ) -> WorkflowImageRegistry | None:
        registry_service = ContainerRegistryService(self.session)
        registry_id = getattr(workflow, "container_registry_id", None)
        if registry_id:
            material = await registry_service.resolve_auth_material(str(registry_id))
            return workflow_registry_from_auth_material(material)
        registry = await registry_service.get_effective_registry(project_id=project_id)
        if registry is None:
            return None
        material = await registry_service.resolve_auth_material(str(registry.id))
        return workflow_registry_from_auth_material(material)

    @staticmethod
    def _write_json(path: Path, payload: dict) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    def _resolve_manual_path(self, raw: str, *, project, field: FormField) -> Path:
        text = raw.strip()
        if _is_absolute_or_home_path(text):
            candidate = self._resolve_absolute_manual_path(
                text,
                project=project,
                field=field,
            )
            if not candidate.exists():
                raise FileNotFoundError(f"path not found: {raw}")
            return candidate

        for root in self._allowed_roots(project=project, field=field):
            try:
                candidate = safe_join(
                    root,
                    text,
                    escape_message="path escapes allowed storage roots",
                )
            except PermissionError:
                continue
            if candidate.exists():
                return candidate

        raise FileNotFoundError(f"path not found within allowed storage roots: {raw}")

    def _validate_allowed_path(self, path: Path, *, project, field: FormField) -> None:
        allowed_roots = self._allowed_roots(project=project, field=field)
        candidate = path
        if not any(self._path_under_root(candidate, root) for root in allowed_roots):
            raise CompileError(
                RunErrorCode.PATH_OUTSIDE_ALLOWED_ROOT,
                f"path is outside allowed storage roots: {path}",
                hint="Choose a path from the workflow field's allowed storage roots.",
            )

    def _allowed_roots(self, *, project, field: FormField) -> tuple[Path, ...]:
        requested = list(field.allow_roots or ["any_allowed_root"])
        roots: list[Path] = []

        for allow_root in requested:
            if allow_root == "project_data":
                roots.append(project_data_root(project))
            elif allow_root == "shared_data":
                roots.append(deliveries_root())
            elif allow_root == "reference":
                roots.append(reference_root())
            elif allow_root == "database":
                roots.append(database_root())
            elif allow_root == "any_allowed_root":
                roots.extend(
                    (
                        project_data_root(project),
                        deliveries_root(),
                        reference_root(),
                        database_root(),
                    )
                )

        deduped: list[Path] = []
        seen: set[str] = set()
        for root in roots:
            resolved = str(root.resolve())
            if resolved in seen:
                continue
            seen.add(resolved)
            deduped.append(root.resolve())
        return tuple(deduped)

    def _resolve_absolute_manual_path(
        self, raw: str, *, project, field: FormField
    ) -> Path:
        if "\x00" in raw:
            raise FileNotFoundError("path not found within allowed storage roots")

        expanded = os.path.realpath(os.path.expanduser(raw))
        allowed_roots = self._allowed_roots(project=project, field=field)
        for root in allowed_roots:
            root_real = os.path.realpath(root)
            try:
                is_under_root = os.path.commonpath([expanded, root_real]) == root_real
            except ValueError:
                is_under_root = False
            if not is_under_root:
                continue
            candidate = safe_join(
                root,
                os.path.relpath(expanded, root_real),
                escape_message="path escapes allowed storage roots",
            )
            if self._path_under_root(candidate, root):
                return candidate
        raise FileNotFoundError("path not found within allowed storage roots")

    @staticmethod
    def _path_under_root(path: Path, root: Path) -> bool:
        try:
            return path.is_relative_to(root.resolve())
        except ValueError:
            return False


def _render_csv(rows: Sequence[Mapping[str, str]]) -> str:
    rows = [dict(row) for row in rows]
    columns: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for column in row.keys():
            if column not in seen:
                columns.append(str(column))
                seen.add(str(column))
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=columns, extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        writer.writerow({column: str(row.get(column, "")) for column in columns})
    return buffer.getvalue()


def _reserve_fresh_run_layout(project, *, engine: str) -> tuple[str, RunLayout]:
    for _ in range(16):
        run_id = generate_run_id()
        try:
            ensure_run_layout(project, run_id, engine=engine)
        except FileExistsError:
            continue
        return run_id, RunLayout.for_run(project, run_id, engine)
    raise RuntimeError("could not allocate a unique run directory")


def _optional_nextflow_revision(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text or text.lower() == "latest":
        return None
    return text


def _optional_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _validate_form_values(values: dict[str, Any], spec: FormSpec) -> None:
    fields_by_id = {field.id: field for field in spec.fields}
    user_fields = [field for field in spec.fields if not field.platform_managed]
    if not user_fields:
        return

    for field_id in values:
        field = fields_by_id.get(field_id)
        if field is None:
            raise CompileError(
                RunErrorCode.INVALID_FORM_VALUES,
                f"Unknown input: {field_id}",
                hint="Refresh the workflow form and submit again.",
            )
        if field.platform_managed:
            raise CompileError(
                RunErrorCode.INVALID_FORM_VALUES,
                f"{field.label} is managed by the platform",
                hint="Remove the managed field from the submitted values.",
            )

    for field in spec.fields:
        if field.platform_managed:
            continue
        raw = values.get(field.id)
        if field.required and _is_missing_form_value(field, raw):
            raise CompileError(
                RunErrorCode.INVALID_FORM_VALUES,
                f"{field.label} is required",
                hint="Fill in the required workflow inputs before submitting.",
            )
        if _is_missing_form_value(field, raw):
            continue
        _validate_form_value_shape(field, raw)


def _is_missing_form_value(field: FormField, value: Any) -> bool:
    if value is None:
        return True
    if field.kind == "file_list":
        return not isinstance(value, list) or len(value) == 0
    if field.kind == "table":
        return not _table_has_meaningful_rows(value)
    if isinstance(value, str):
        return value.strip() == ""
    return False


def _table_has_meaningful_rows(value: Any) -> bool:
    if not isinstance(value, dict):
        return False
    rows = value.get("rows")
    if not isinstance(rows, list):
        return False
    for row in rows:
        if not isinstance(row, Mapping):
            continue
        if any(str(cell).strip() for cell in row.values() if cell is not None):
            return True
    return False


def _validate_form_value_shape(field: FormField, value: Any) -> None:
    if field.kind in ("file", "directory", "string"):
        if isinstance(value, str):
            return
    elif field.kind == "file_list":
        if isinstance(value, list) and all(
            isinstance(item, str) and item.strip() for item in value
        ):
            return
    elif field.kind == "table":
        if isinstance(value, dict) and isinstance(value.get("rows"), list):
            return
    elif field.kind == "bool":
        if isinstance(value, bool):
            return
    elif field.kind == "int":
        if isinstance(value, int) and not isinstance(value, bool):
            return
    elif field.kind == "float":
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            return
    elif field.kind == "select":
        options = {option.value for option in field.options or []}
        if isinstance(value, str) and value in options:
            return

    raise CompileError(
        RunErrorCode.INVALID_FORM_VALUES,
        f"{field.label} has an invalid value",
        hint="Review the workflow inputs and try again.",
    )


def _merge_values_with_defaults(
    values: Mapping[str, Any], spec: FormSpec
) -> dict[str, Any]:
    merged = dict(values)
    for field in spec.fields:
        if field.platform_managed or field.id in merged or field.default is None:
            continue
        merged[field.id] = deepcopy(field.default)
    return merged


def _required_container_images(
    schema_json: dict | None,
    *,
    image_registry: WorkflowImageRegistry | None = None,
) -> list[Any]:
    if image_registry is not None:
        return runtime_workflow_container_images(
            schema_json,
            default_registry=image_registry,
        )
    return workflow_container_images(schema_json)


def _set_config_override(config: dict, key: str, value: Any) -> None:
    overrides = dict(config.get("config_overrides") or {})
    overrides[key] = value
    config["config_overrides"] = overrides

    request = dict(config.get("request") or {})
    request_overrides = dict(request.get("config_overrides") or {})
    request_overrides[key] = value
    request["config_overrides"] = request_overrides
    config["request"] = request


def _merge_config_patch(config: dict, patch: dict) -> dict:
    merged = dict(config)
    for key, value in patch.items():
        if (
            isinstance(value, dict)
            and isinstance(merged.get(key), dict)
            and key in {"runtime", "policy", "ui"}
        ):
            merged[key] = {**merged[key], **value}
        else:
            merged[key] = deepcopy(value)
    return merged


def _write_resolved_wdl_workflow(
    workflow_path: Path,
    *,
    layout: RunLayout,
    image_registry: WorkflowImageRegistry,
) -> Path:
    if not workflow_path.is_file():
        return workflow_path
    content = workflow_path.read_text(encoding="utf-8")
    resolved = rewrite_wdl_static_container_literals(
        content,
        default_registry=image_registry,
    )
    if resolved == content:
        return workflow_path
    target = layout.engine_workspace.parent / "workflow.resolved.wdl"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(resolved, encoding="utf-8")
    return target


def _is_absolute_or_home_path(value: str) -> bool:
    return (
        value.startswith("~")
        or PurePosixPath(value).is_absolute()
        or PureWindowsPath(value).is_absolute()
    )
