import { renderHook, waitFor, act } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { useProjectContext } from "@/components/bioinfoflow/project-context"
import { useSidebarData } from "@/hooks/use-sidebar-data"
import { apiRequest } from "@/lib/api"
import { emitConversationUpdated } from "@/lib/conversations"
import type { AgentConversationRead, Project } from "@/lib/types"
import { createAppWrapper } from "@/tests/app-test-utils"

const { pushMock, toastErrorMock, toastSuccessMock } = vi.hoisted(() => ({
  pushMock: vi.fn(),
  toastErrorMock: vi.fn(),
  toastSuccessMock: vi.fn(),
}))

vi.mock("next/navigation", () => ({
  useRouter: () => ({ push: pushMock }),
}))

vi.mock("sonner", () => ({
  toast: {
    error: toastErrorMock,
    success: toastSuccessMock,
  },
}))

vi.mock("@/lib/api", async () => {
  const actual = await vi.importActual<typeof import("@/lib/api")>("@/lib/api")
  return {
    ...actual,
    apiRequest: vi.fn(),
  }
})

describe("useSidebarData", () => {
  const apiRequestMock = vi.mocked(apiRequest)
  const tSidebar = (key: string, values?: Record<string, string>) =>
    values?.name ? `${key}:${values.name}` : key

  beforeEach(() => {
    apiRequestMock.mockReset()
    pushMock.mockReset()
    toastErrorMock.mockReset()
    toastSuccessMock.mockReset()
    window.localStorage.clear()
  })

  afterEach(() => {
    vi.clearAllMocks()
  })

  it("sorts projects alphabetically without prefix-based special cases", async () => {
    const projects: Project[] = [
      { id: "project-default", name: "Recent", project_root: "asset://project", storage_mode: "managed", is_default: true },
      { id: "project-z", name: "Zeta", project_root: "asset://project", storage_mode: "managed" },
      { id: "project-demo", name: "Archive/Alpha", project_root: "asset://project", storage_mode: "managed" },
      { id: "project-a", name: "Alpha", project_root: "asset://project", storage_mode: "managed" },
    ]

    apiRequestMock.mockImplementation(async (path) => {
      if (path === "/projects") {
        return { data: projects, meta: undefined }
      }
      if (path === "/projects/default") {
        return { data: projects[0], meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [], meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper()
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() =>
      expect(result.current.sidebar.projects.map((project) => project.id)).toEqual([
        "project-a",
        "project-demo",
        "project-z",
      ])
    )

    expect(result.current.project.selectedProjectId).toBe("")
    expect(result.current.project.conversationProjectId).toBe("")
    expect(result.current.project.activeProjectName).toBe("")
  })

  it("restores the stored conversation for the active project when available", async () => {
    const projects: Project[] = [
      { id: "project-1", name: "Alpha", project_root: "asset://project", storage_mode: "managed" },
    ]
    const conversations: AgentConversationRead[] = [
      { id: "conversation-1", project_id: "project-1", title: "First" },
      { id: "conversation-2", project_id: "project-1", title: "Second" },
    ]

    window.localStorage.setItem("bioinfoflow:conversation:project-1", "conversation-2")

    apiRequestMock.mockImplementation(async (path) => {
      if (path === "/projects") {
        return { data: projects, meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: conversations, meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper({
      activeProjectId: "project-1",
    })

    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() =>
      expect(result.current.project.activeConversationId).toBe("conversation-2")
    )
    expect(result.current.project.activeConversationTitle).toBe("Second")
  })

  it("creates a project without requiring workspace (auto-generated by dialog)", async () => {
    const apiProjects: Project[] = []
    const createdProject: Project = {
      id: "project-new",
      name: "My Analysis",
      project_root: "asset://project",
      storage_mode: "managed",
    }

    apiRequestMock.mockImplementation(async (path, options) => {
      if (path === "/projects" && options?.method === "POST") {
        return { data: createdProject, meta: undefined }
      }
      if (path === "/projects") {
        return { data: apiProjects, meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [], meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper()
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() => expect(result.current.sidebar.isLoading).toBe(false))

    // Should NOT throw when workspace is empty
    await act(async () => {
      await result.current.sidebar.handleCreateProject({
        name: "My Analysis",
        description: "",
        storageOverridePath: "",
      })
    })

    expect(toastErrorMock).not.toHaveBeenCalled()
    expect(toastSuccessMock).toHaveBeenCalled()
  })

  it("quick-creates a project with only name and description (no workspace)", async () => {
    const createdProject: Project = {
      id: "project-quick",
      name: "WGS Analysis",
      project_root: "asset://project",
      storage_mode: "managed",
    }

    apiRequestMock.mockImplementation(async (path, options) => {
      if (path === "/projects" && options?.method === "POST") {
        return { data: createdProject, meta: undefined }
      }
      if (path === "/projects") {
        return { data: [], meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [], meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper()
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() => expect(result.current.sidebar.isLoading).toBe(false))

    await act(async () => {
      await result.current.sidebar.handleQuickCreateProject({
        name: "WGS Analysis",
        description: "Whole genome sequencing variant calling",
      })
    })

    // Should POST with name and description only (no workspace_path)
    const postCall = apiRequestMock.mock.calls.find(
      ([path, opts]) => path === "/projects" && opts?.method === "POST"
    )
    expect(postCall).toBeDefined()
    const body = JSON.parse(postCall![1]!.body as string)
    expect(body).toEqual({
      name: "WGS Analysis",
      description: "Whole genome sequencing variant calling",
    })
    expect(body).not.toHaveProperty("workspace_path")

    expect(toastSuccessMock).toHaveBeenCalled()
    expect(result.current.project.activeProjectId).toBe("project-quick")
  })

  it("creates an inbox conversation when no real project is selected", async () => {
    const defaultProject: Project = {
      id: "project-default",
      name: "Recent",
      project_root: "asset://project",
      storage_mode: "managed",
      is_default: true,
    }
    const createdConversation: AgentConversationRead = {
      id: "conversation-inbox",
      project_id: defaultProject.id,
      title: "Inbox analysis",
    }

    apiRequestMock.mockImplementation(async (path, options) => {
      if (path === "/projects") {
        return { data: [defaultProject], meta: undefined }
      }
      if (path === "/projects/default") {
        return { data: defaultProject, meta: undefined }
      }
      if (path === "/agent/conversations" && options?.method === "POST") {
        return { data: createdConversation, meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [], meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper()
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() => expect(result.current.sidebar.defaultProject?.id).toBe("project-default"))

    await act(async () => {
      await result.current.sidebar.handleCreateConversation()
    })

    const postCall = apiRequestMock.mock.calls.find(
      ([path, opts]) => path === "/agent/conversations" && opts?.method === "POST"
    )
    expect(postCall).toBeDefined()
    expect(JSON.parse(postCall![1]!.body as string)).toEqual({})
    expect(result.current.project.selectedProjectId).toBe("")
    expect(result.current.project.conversationProjectId).toBe("project-default")
    expect(result.current.project.activeConversationId).toBe("conversation-inbox")
    expect(window.localStorage.getItem("bioinfoflow:conversation:project-default")).toBe("conversation-inbox")
    expect(pushMock).toHaveBeenCalledWith("/agent")
  })

  it("deletes the previous unsent draft conversation before creating another", async () => {
    const project: Project = {
      id: "project-1",
      name: "Alpha",
      project_root: "asset://project",
      storage_mode: "managed",
    }
    const createdConversations: AgentConversationRead[] = [
      { id: "conversation-draft-1", project_id: project.id, title: null },
      { id: "conversation-draft-2", project_id: project.id, title: null },
    ]
    let createIndex = 0

    apiRequestMock.mockImplementation(async (path, options) => {
      if (path === "/projects") {
        return { data: [project], meta: undefined }
      }
      if (path === "/projects/default") {
        throw new Error("no default")
      }
      if (path === "/agent/conversations" && options?.method === "POST") {
        const conversation = createdConversations[createIndex++]
        return { data: conversation, meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [], meta: undefined }
      }
      if (path === "/agent/conversations/conversation-draft-1" && options?.method === "DELETE") {
        return { data: null, meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper({ selectedProjectId: "project-1" })
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() => expect(result.current.sidebar.projects).toHaveLength(1))

    await act(async () => {
      await result.current.sidebar.handleCreateConversation(project.id)
    })
    await act(async () => {
      await result.current.sidebar.handleCreateConversation(project.id)
    })

    expect(apiRequestMock).toHaveBeenCalledWith(
      "/agent/conversations/conversation-draft-1",
      { method: "DELETE" },
    )
    expect(result.current.sidebar.projectConversations.get(project.id)).toEqual([
      createdConversations[1],
    ])
    expect(window.localStorage.getItem("bioinfoflow:conversation:project-1")).toBe("conversation-draft-2")
  })

  it("keeps a draft conversation after it receives a title update", async () => {
    const project: Project = {
      id: "project-1",
      name: "Alpha",
      project_root: "asset://project",
      storage_mode: "managed",
    }
    const createdConversations: AgentConversationRead[] = [
      { id: "conversation-draft-1", project_id: project.id, title: null },
      { id: "conversation-draft-2", project_id: project.id, title: null },
    ]
    let createIndex = 0

    apiRequestMock.mockImplementation(async (path, options) => {
      if (path === "/projects") {
        return { data: [project], meta: undefined }
      }
      if (path === "/projects/default") {
        throw new Error("no default")
      }
      if (path === "/agent/conversations" && options?.method === "POST") {
        const conversation = createdConversations[createIndex++]
        return { data: conversation, meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [], meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper({ selectedProjectId: "project-1" })
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() => expect(result.current.sidebar.projects).toHaveLength(1))

    await act(async () => {
      await result.current.sidebar.handleCreateConversation(project.id)
    })
    act(() => {
      emitConversationUpdated({
        id: "conversation-draft-1",
        project_id: project.id,
        title: "Started analysis",
      })
    })
    await act(async () => {
      await result.current.sidebar.handleCreateConversation(project.id)
    })

    expect(
      apiRequestMock.mock.calls.some(
        ([path, options]) =>
          path === "/agent/conversations/conversation-draft-1" &&
          options?.method === "DELETE",
      ),
    ).toBe(false)
    expect(result.current.sidebar.projectConversations.get(project.id)).toEqual([
      createdConversations[1],
      { ...createdConversations[0], title: "Started analysis" },
    ])
  })

  it("deletes an existing active empty conversation before creating another", async () => {
    const project: Project = {
      id: "project-1",
      name: "Alpha",
      project_root: "asset://project",
      storage_mode: "managed",
    }
    const emptyConversation: AgentConversationRead = {
      id: "conversation-empty",
      project_id: project.id,
      title: null,
    }
    const newConversation: AgentConversationRead = {
      id: "conversation-new",
      project_id: project.id,
      title: null,
    }

    apiRequestMock.mockImplementation(async (path, options) => {
      if (path === "/projects") {
        return { data: [project], meta: undefined }
      }
      if (path === "/projects/default") {
        throw new Error("no default")
      }
      if (path === "/agent/conversations/conversation-empty" && options?.method === "DELETE") {
        return { data: null, meta: undefined }
      }
      if (path === "/agent/conversations/conversation-empty") {
        return {
          data: {
            conversation_id: emptyConversation.id,
            project_id: project.id,
            title: null,
            messages: [],
          },
          meta: undefined,
        }
      }
      if (path === "/agent/conversations" && options?.method === "POST") {
        return { data: newConversation, meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [emptyConversation], meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper({
      selectedProjectId: "project-1",
      conversationProjectId: "project-1",
      activeConversationId: "conversation-empty",
    })
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() =>
      expect(result.current.sidebar.projectConversations.get(project.id)).toEqual([
        emptyConversation,
      ])
    )

    await act(async () => {
      await result.current.sidebar.handleCreateConversation(project.id)
    })

    expect(apiRequestMock).toHaveBeenCalledWith(
      "/agent/conversations/conversation-empty",
      { method: "DELETE" },
    )
    expect(result.current.sidebar.projectConversations.get(project.id)).toEqual([
      newConversation,
    ])
  })

  it("selects a conversation, persists it, and navigates to the agent page", async () => {
    const apiProjects: Project[] = [{ id: "project-1", name: "Alpha", project_root: "asset://project" }]

    apiRequestMock.mockImplementation(async (path) => {
      if (path === "/projects") {
        return { data: apiProjects, meta: undefined }
      }
      if (path === "/agent/conversations") {
        return { data: [], meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper()
    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )
    const conversation: AgentConversationRead = {
      id: "conversation-9",
      project_id: "project-1",
      title: "Genome QC",
    }

    await waitFor(() => expect(result.current.sidebar.projects).toHaveLength(1))

    act(() => {
      result.current.sidebar.handleSelectConversation(conversation, "project-1")
    })

    expect(result.current.project.activeProjectId).toBe("project-1")
    expect(result.current.project.activeConversationId).toBe("conversation-9")
    expect(window.localStorage.getItem("bioinfoflow:conversation:project-1")).toBe("conversation-9")
    expect(pushMock).toHaveBeenCalledWith("/agent")
  })

  it("updates sidebar conversation titles when the active chat emits a title refresh", async () => {
    const apiProjects: Project[] = [{ id: "project-1", name: "Alpha", project_root: "asset://project" }]
    const conversations: AgentConversationRead[] = [
      { id: "conversation-1", project_id: "project-1", title: null },
    ]

    apiRequestMock.mockImplementation(async (path) => {
      if (path === "/projects") {
        return { data: apiProjects, meta: undefined }
      }
      if (path === "/projects/default") {
        throw new Error("no default")
      }
      if (path === "/agent/conversations") {
        return { data: conversations, meta: undefined }
      }
      throw new Error(`Unexpected path: ${path}`)
    })

    const Wrapper = createAppWrapper({
      selectedProjectId: "project-1",
      conversationProjectId: "project-1",
      activeConversationId: "conversation-1",
    })

    const { result } = renderHook(
      () => ({ sidebar: useSidebarData(tSidebar), project: useProjectContext() }),
      { wrapper: Wrapper }
    )

    await waitFor(() =>
      expect(result.current.project.activeConversationTitle).toBe("")
    )

    act(() => {
      emitConversationUpdated({
        id: "conversation-1",
        project_id: "project-1",
        title: "RNA-seq QC Plan",
      })
    })

    await waitFor(() =>
      expect(result.current.project.activeConversationTitle).toBe("RNA-seq QC Plan")
    )
  })
})
