"use client"

export const appearancePresetIds = [
  "notion",
  "github",
  "linear",
  "one",
  "vercel",
] as const

export type ThemePresetId = (typeof appearancePresetIds)[number]

export const APPEARANCE_TOKEN_KEYS = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "border",
  "input",
  "ring",
  "sidebar",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-ring",
  "surface-elevated",
  "surface-subtle",
  "text-primary",
  "text-secondary",
  "text-muted",
  "divider",
  "announcement-bg",
  "announcement-fg",
  "bg",
  "bg-elevated",
  "bg-surface",
  "bg-subtle",
  "bg-hover",
  "bg-active",
  "fg",
  "fg-secondary",
  "fg-muted",
  "fg-subtle",
  "fg-faint",
  "border-subtle",
  "border-hover",
  "accent-muted",
  "accent-subtle",
  "accent-hover",
  "terminal-background",
  "terminal-foreground",
  "terminal-cursor",
  "terminal-selection",
] as const

export type AppearanceTokenKey = (typeof APPEARANCE_TOKEN_KEYS)[number]
export type AppearanceTokens = Record<AppearanceTokenKey, string>

type AppearancePreset = {
  id: ThemePresetId
  label: string
  light: AppearanceTokens
  dark: AppearanceTokens
}

type ModeSeed = {
  background: string
  elevated: string
  surface: string
  subtle: string
  hover: string
  active: string
  foreground: string
  secondaryForeground: string
  mutedForeground: string
  subtleForeground: string
  faintForeground: string
  border: string
  borderSubtle: string
  borderHover: string
  accent: string
  accentMuted: string
  accentSubtle: string
  accentHover: string
  ring: string
  sidebar: string
  sidebarAccent: string
  sidebarBorder: string
  primary?: string
  primaryForeground?: string
  announcementBg?: string
  announcementFg?: string
  terminalBackground?: string
  terminalForeground?: string
  terminalCursor?: string
  terminalSelection?: string
}

function createTokens(seed: ModeSeed): AppearanceTokens {
  const primary = seed.primary ?? seed.foreground
  const primaryForeground = seed.primaryForeground ?? seed.background
  const announcementBg = seed.announcementBg ?? primary
  const announcementFg = seed.announcementFg ?? primaryForeground

  return {
    "background": seed.background,
    "foreground": seed.foreground,
    "card": seed.elevated,
    "card-foreground": seed.foreground,
    "popover": seed.elevated,
    "popover-foreground": seed.foreground,
    "primary": primary,
    "primary-foreground": primaryForeground,
    "secondary": seed.surface,
    "secondary-foreground": seed.foreground,
    "muted": seed.surface,
    "muted-foreground": seed.mutedForeground,
    "accent": seed.accent,
    "accent-foreground": seed.foreground,
    "border": seed.border,
    "input": seed.border,
    "ring": seed.ring,
    "sidebar": seed.sidebar,
    "sidebar-foreground": seed.foreground,
    "sidebar-primary": primary,
    "sidebar-primary-foreground": primaryForeground,
    "sidebar-accent": seed.sidebarAccent,
    "sidebar-accent-foreground": seed.foreground,
    "sidebar-border": seed.sidebarBorder,
    "sidebar-ring": seed.ring,
    "surface-elevated": seed.elevated,
    "surface-subtle": seed.subtle,
    "text-primary": seed.foreground,
    "text-secondary": seed.secondaryForeground,
    "text-muted": seed.mutedForeground,
    "divider": seed.borderSubtle,
    "announcement-bg": announcementBg,
    "announcement-fg": announcementFg,
    "bg": seed.background,
    "bg-elevated": seed.elevated,
    "bg-surface": seed.surface,
    "bg-subtle": seed.subtle,
    "bg-hover": seed.hover,
    "bg-active": seed.active,
    "fg": seed.foreground,
    "fg-secondary": seed.secondaryForeground,
    "fg-muted": seed.mutedForeground,
    "fg-subtle": seed.subtleForeground,
    "fg-faint": seed.faintForeground,
    "border-subtle": seed.borderSubtle,
    "border-hover": seed.borderHover,
    "accent-muted": seed.accentMuted,
    "accent-subtle": seed.accentSubtle,
    "accent-hover": seed.accentHover,
    "terminal-background": seed.terminalBackground ?? seed.elevated,
    "terminal-foreground": seed.terminalForeground ?? seed.foreground,
    "terminal-cursor": seed.terminalCursor ?? seed.foreground,
    "terminal-selection":
      seed.terminalSelection ?? (seed.background === "#ffffff" ? "rgba(15, 23, 42, 0.12)" : "rgba(148, 163, 184, 0.35)"),
  }
}

function createPreset(
  id: ThemePresetId,
  label: string,
  light: ModeSeed,
  dark: ModeSeed,
): AppearancePreset {
  return {
    id,
    label,
    light: createTokens(light),
    dark: createTokens(dark),
  }
}

export const appearancePresets: Record<ThemePresetId, AppearancePreset> = {
  linear: createPreset(
    "linear",
    "Linear",
    {
      background: "#f7f8fb",
      elevated: "#ffffff",
      surface: "#eef1f7",
      subtle: "#f4f6fa",
      hover: "#e8ecf5",
      active: "#dfe6f2",
      foreground: "#111827",
      secondaryForeground: "#334155",
      mutedForeground: "#64748b",
      subtleForeground: "#7c8aa0",
      faintForeground: "#94a3b8",
      border: "#dde4f0",
      borderSubtle: "#e8edf4",
      borderHover: "#c8d4e6",
      accent: "#ebf1ff",
      accentMuted: "rgba(37, 99, 235, 0.08)",
      accentSubtle: "rgba(37, 99, 235, 0.04)",
      accentHover: "rgba(37, 99, 235, 0.12)",
      ring: "#2563eb",
      sidebar: "#f3f5fa",
      sidebarAccent: "#e7ecf6",
      sidebarBorder: "#dbe2ed",
      primary: "#2563eb",
      primaryForeground: "#eff6ff",
      announcementBg: "#111827",
      announcementFg: "#f8fafc",
    },
    {
      background: "#0d0f14",
      elevated: "#12151d",
      surface: "#171b24",
      subtle: "#1c2230",
      hover: "#22293a",
      active: "#293347",
      foreground: "#f3f4f6",
      secondaryForeground: "#d1d5db",
      mutedForeground: "#94a3b8",
      subtleForeground: "#7b879c",
      faintForeground: "#64748b",
      border: "#212838",
      borderSubtle: "#1a2030",
      borderHover: "#334155",
      accent: "#18223c",
      accentMuted: "rgba(96, 165, 250, 0.10)",
      accentSubtle: "rgba(96, 165, 250, 0.06)",
      accentHover: "rgba(96, 165, 250, 0.16)",
      ring: "#60a5fa",
      sidebar: "#0b0f18",
      sidebarAccent: "#161e2d",
      sidebarBorder: "#1f2937",
      primary: "#60a5fa",
      primaryForeground: "#0b1120",
      announcementBg: "#131827",
      announcementFg: "#eff6ff",
    },
  ),
  github: createPreset(
    "github",
    "GitHub",
    {
      background: "#ffffff",
      elevated: "#ffffff",
      surface: "#f6f8fa",
      subtle: "#f6f8fa",
      hover: "#eef2f6",
      active: "#e3e9ef",
      foreground: "#1f2328",
      secondaryForeground: "#424a53",
      mutedForeground: "#59636e",
      subtleForeground: "#6e7781",
      faintForeground: "#8c959f",
      border: "#d0d7de",
      borderSubtle: "#d8dee4",
      borderHover: "#afb8c1",
      accent: "#ddf4ff",
      accentMuted: "rgba(9, 105, 218, 0.08)",
      accentSubtle: "rgba(9, 105, 218, 0.04)",
      accentHover: "rgba(9, 105, 218, 0.14)",
      ring: "#0969da",
      sidebar: "#f6f8fa",
      sidebarAccent: "#eef2f6",
      sidebarBorder: "#d8dee4",
      primary: "#0969da",
      primaryForeground: "#eff6ff",
      announcementBg: "#24292f",
      announcementFg: "#f6f8fa",
    },
    {
      background: "#0d1117",
      elevated: "#161b22",
      surface: "#161b22",
      subtle: "#0f141b",
      hover: "#1f2630",
      active: "#263040",
      foreground: "#e6edf3",
      secondaryForeground: "#c9d1d9",
      mutedForeground: "#8b949e",
      subtleForeground: "#7d8590",
      faintForeground: "#6e7681",
      border: "#30363d",
      borderSubtle: "#21262d",
      borderHover: "#8b949e",
      accent: "#1f6feb1f",
      accentMuted: "rgba(47, 129, 247, 0.10)",
      accentSubtle: "rgba(47, 129, 247, 0.05)",
      accentHover: "rgba(47, 129, 247, 0.16)",
      ring: "#2f81f7",
      sidebar: "#010409",
      sidebarAccent: "#161b22",
      sidebarBorder: "#30363d",
      primary: "#2f81f7",
      primaryForeground: "#08111f",
      announcementBg: "#1f6feb",
      announcementFg: "#f0f6fc",
    },
  ),
  notion: createPreset(
    "notion",
    "Notion",
    {
      background: "#ffffff",
      elevated: "#ffffff",
      surface: "#f7f7f5",
      subtle: "#fbfbfa",
      hover: "#f1f1ef",
      active: "#e9e9e7",
      foreground: "#191919",
      secondaryForeground: "#37352f",
      mutedForeground: "#6f6e69",
      subtleForeground: "#8b8a87",
      faintForeground: "#a8a7a3",
      border: "#e9e9e7",
      borderSubtle: "#efefec",
      borderHover: "#d4d4d1",
      accent: "#f1f1ef",
      accentMuted: "rgba(25,25,25,0.05)",
      accentSubtle: "rgba(25,25,25,0.03)",
      accentHover: "rgba(25,25,25,0.08)",
      ring: "#6f6e69",
      sidebar: "#fbfbfa",
      sidebarAccent: "#f1f1ef",
      sidebarBorder: "#ebebe8",
      announcementBg: "#191919",
      announcementFg: "#ffffff",
    },
    {
      background: "#191919",
      elevated: "#202020",
      surface: "#242424",
      subtle: "#2a2a2a",
      hover: "#313131",
      active: "#3a3a3a",
      foreground: "#f1f1ef",
      secondaryForeground: "#d4d4d1",
      mutedForeground: "#a9a8a4",
      subtleForeground: "#8b8a87",
      faintForeground: "#6f6e69",
      border: "#373737",
      borderSubtle: "#2c2c2c",
      borderHover: "#525252",
      accent: "#2c2c2c",
      accentMuted: "rgba(255,255,255,0.06)",
      accentSubtle: "rgba(255,255,255,0.03)",
      accentHover: "rgba(255,255,255,0.10)",
      ring: "#a9a8a4",
      sidebar: "#181818",
      sidebarAccent: "#252525",
      sidebarBorder: "#303030",
      announcementBg: "#f1f1ef",
      announcementFg: "#191919",
    },
  ),
  one: createPreset(
    "one",
    "One",
    {
      background: "#fafafa",
      elevated: "#ffffff",
      surface: "#f0f2f6",
      subtle: "#f5f7fb",
      hover: "#e8ecf3",
      active: "#dce3ed",
      foreground: "#282c34",
      secondaryForeground: "#3e4451",
      mutedForeground: "#5c6370",
      subtleForeground: "#6b7280",
      faintForeground: "#9aa3b2",
      border: "#d7dce3",
      borderSubtle: "#e6eaf0",
      borderHover: "#c1c9d4",
      accent: "#eaf0ff",
      accentMuted: "rgba(97, 175, 239, 0.08)",
      accentSubtle: "rgba(97, 175, 239, 0.04)",
      accentHover: "rgba(97, 175, 239, 0.14)",
      ring: "#61afef",
      sidebar: "#f3f5f8",
      sidebarAccent: "#e8edf4",
      sidebarBorder: "#dde3eb",
      primary: "#4f8cc9",
      primaryForeground: "#f8fafc",
      announcementBg: "#282c34",
      announcementFg: "#f8fafc",
    },
    {
      background: "#282c34",
      elevated: "#2c313c",
      surface: "#313640",
      subtle: "#262a33",
      hover: "#353b45",
      active: "#3e4451",
      foreground: "#abb2bf",
      secondaryForeground: "#c8ced9",
      mutedForeground: "#9da5b4",
      subtleForeground: "#7f8796",
      faintForeground: "#6b7280",
      border: "#3e4451",
      borderSubtle: "#353b45",
      borderHover: "#4b5263",
      accent: "#2f3645",
      accentMuted: "rgba(97, 175, 239, 0.10)",
      accentSubtle: "rgba(97, 175, 239, 0.05)",
      accentHover: "rgba(97, 175, 239, 0.16)",
      ring: "#61afef",
      sidebar: "#21252b",
      sidebarAccent: "#313640",
      sidebarBorder: "#3e4451",
      primary: "#61afef",
      primaryForeground: "#111827",
      announcementBg: "#61afef",
      announcementFg: "#111827",
    },
  ),
  vercel: createPreset(
    "vercel",
    "Vercel",
    {
      background: "#ffffff",
      elevated: "#fafafa",
      surface: "#f5f5f5",
      subtle: "#fafafa",
      hover: "#f1f1f1",
      active: "#ebebeb",
      foreground: "#111111",
      secondaryForeground: "#262626",
      mutedForeground: "#525252",
      subtleForeground: "#737373",
      faintForeground: "#a3a3a3",
      border: "#e5e5e5",
      borderSubtle: "#f0f0f0",
      borderHover: "#d4d4d4",
      accent: "#f4f4f5",
      accentMuted: "rgba(0, 0, 0, 0.05)",
      accentSubtle: "rgba(0, 0, 0, 0.03)",
      accentHover: "rgba(0, 0, 0, 0.08)",
      ring: "#171717",
      sidebar: "#fafafa",
      sidebarAccent: "#f1f1f1",
      sidebarBorder: "#e5e5e5",
      primary: "#111111",
      primaryForeground: "#fafafa",
      announcementBg: "#111111",
      announcementFg: "#fafafa",
    },
    {
      background: "#000000",
      elevated: "#0a0a0a",
      surface: "#111111",
      subtle: "#080808",
      hover: "#171717",
      active: "#1f1f1f",
      foreground: "#fafafa",
      secondaryForeground: "#e5e5e5",
      mutedForeground: "#a3a3a3",
      subtleForeground: "#737373",
      faintForeground: "#525252",
      border: "#262626",
      borderSubtle: "#171717",
      borderHover: "#404040",
      accent: "#111111",
      accentMuted: "rgba(255, 255, 255, 0.06)",
      accentSubtle: "rgba(255, 255, 255, 0.03)",
      accentHover: "rgba(255, 255, 255, 0.10)",
      ring: "#f5f5f5",
      sidebar: "#000000",
      sidebarAccent: "#111111",
      sidebarBorder: "#262626",
      primary: "#fafafa",
      primaryForeground: "#0a0a0a",
      announcementBg: "#fafafa",
      announcementFg: "#0a0a0a",
      terminalBackground: "#000000",
      terminalForeground: "#fafafa",
      terminalCursor: "#fafafa",
      terminalSelection: "rgba(255, 255, 255, 0.14)",
    },
  ),
}
